services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "guest"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "my-db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: "postgres"
      DB_NAME: "my-db"
      DB_USER: "guest"
      DB_PASSWORD: "password"
    depends_on:
      - postgres

volumes:
  postgres_data:
